baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Adil Naimi"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Adil Naimi"
    subtitle = "Personal welcome page"
    keywords = ""
    copyright = ""
    # readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"

# And you can even create generic menu
# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "/about"
#   [[menu.main]]
#     identifier = "blog"
#     name       = "Blog"
#     url        = "/posts"

  [params.logo]
    logoText     = "$ cd ~"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/adilr00t/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/adilnaimi/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/adilnaimi/"